# Windows (hyprland)
$window_border_color_active = rgba(00FFFFFF)
$window_border_color_active_gradient = rgba(77777744)
$window_border_color_inactive = $window_border_color_active_gradient
$window_border_color_inactive_gradient = $window_border_color_active_gradient
$window_gaps_in = 5
$window_gaps_out = $window_gaps_in
$window_border_size = 2
$window_rounding = 10
$window_rounding_power = 2
$window_active_opacity = 1.0
$window_inactive_opacity = 0.9
$window_shadow_enabled = true
$window_shadow_range = 8
$window_shadow_render_power = 3
$window_shadow_color = rgba(00FFFFAA)
$window_shadow_color_inactive = rgba(00000000)
$window_blur_enabled = true
$window_blur_size = 3
$window_blur_passes = 1
$window_blur_vibrancy = 0.1696

# Wallpaper (hyprpaper)
$wallpaper_file = $HOME/.config/backgrounds/arch-cyan.png

# Lock Screen (hyprlock)
$lockscreen_background_path = $wallpaper_file
# path OR color
$lockscreen_background_color = # rgba(FFFFFFFF)
$lockscreen_background_blur_passes = 2
$lockscreen_background_contrast = 1
$lockscreen_background_brightness = 0.5
$lockscreen_background_vibrancy = 0.2
$lockscreen_background_vibrancy_darkness = 0.2
# Lockscreen Input
$lockscreen_input_size = 250, 60
$lockscreen_input_outline_thikness = 2
$lockscreen_input_dots_size = 0.2 # Scale of input-field height, 0.2 - 0.8
$lockscreen_input_dots_spacing = 0.35 # Scale of dots' absolute size, 0.0 - 1.0
$lockscreen_input_dots_center = true
$lockscreen_input_font_color = rgba(F0F0F0FF)
$lockscreen_input_outer_color = $lockscreen_input_font_color
$lockscreen_input_inner_color = rgba(00000044)
$lockscreen_input_fade_on_empty = true
$lockscreen_input_rounding = 8
$lockscreen_input_check_color = rgba(AA3333FF)
$lockscreen_input_placeholder_text = . . .
# $lockscreen_input_placeholder_text = <i><span foreground="##cdd6f4">Input Password...</span></i>
$lockscreen_input_hide_input = false
$lockscreen_input_position = 0, -200
$lockscreen_input_halign = center
$lockscreen_input_valign = center
# Lockscreen Date
$lockscreen_label_date_text = cmd[update:1000] echo "$(date +"%A, %B %d")"
$lockscreen_label_date_color = $lockscreen_input_font_color
$lockscreen_label_date_font_size = 22
$lockscreen_label_date_font_family = JetBrainsMono Nerd Font Mono
$lockscreen_label_date_position = 0, 300
$lockscreen_label_date_halign = center
$lockscreen_label_date_valign = center
# Lockscreen Time
$lockscreen_label_time_text = cmd[update:1000] echo "$(date +"%-I:%M")"
$lockscreen_label_time_color = $lockscreen_input_font_color
$lockscreen_label_time_font_size = 95
$lockscreen_label_time_font_family = JetBrainsMono Nerd Font Mono
$lockscreen_label_time_position = 0, 200
$lockscreen_label_time_halign = center
$lockscreen_label_time_valign = center

