$wallpaper_file = arch-gray.png

preload = /home/mzvlsmxx/.config/backgrounds/$wallpaper_file
splash = false

wallpaper {
    monitor = eDP-1
    path = /home/mzvlsmxx/.config/backgrounds/$wallpaper_file
}