general {
    # Какую команду выполнять для блокировки
    lock_cmd = pidof hyprlock || hyprlock 
    # Заблокировать перед уходом в сон
    before_sleep_cmd = loginctl lock-session    
    # Разбудить монитор после просыпания
    after_sleep_cmd = hyprctl dispatch dpms on  
}

# Тайм-аут для автоматической блокировки (например, через 5 минут)
listener {
    timeout = 300
    on-timeout = loginctl lock-session
}

# Выключение монитора (через 5.5 минут)
listener {
    timeout = 330
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}
