source = $HOME/.config/hypr/hypr-theme.conf

# BACKGROUND
background {
    monitor =
    path = $lockscreen_background_path
    color = $lockscreen_background_color
    blur_passes = $lockscreen_background_blur_passes
    contrast = $lockscreen_background_contrast
    brightness = $lockscreen_background_brightness
    vibrancy = $lockscreen_background_vibrancy
    vibrancy_darkness = $lockscreen_background_vibrancy_darkness
}

# GENERAL
general {
    no_fade_in = true
    no_fade_out = true
    hide_cursor = false
    grace = 0
    disable_loading_bar = true
}

# INPUT FIELD
input-field {
    monitor =
    size = $lockscreen_input_size
    outline_thickness = $lockscreen_input_outline_thikness
    dots_size = $lockscreen_input_dots_size
    dots_spacing = $lockscreen_input_dots_spacing
    dots_center = $lockscreen_input_dots_center
    outer_color = $lockscreen_input_outer_color
    inner_color = $lockscreen_input_inner_color
    font_color = $lockscreen_input_font_color
    fade_on_empty = $lockscreen_input_fade_on_empty
    rounding = $lockscreen_input_rounding
    check_color = $lockscreen_input_check_color
    placeholder_text = $lockscreen_input_placeholder_text
    hide_input = $lockscreen_input_hide_input
    position = $lockscreen_input_position
    halign = $lockscreen_input_halign
    valign = $lockscreen_input_valign
}

# DATE
label {
  monitor = 
  text = $lockscreen_label_date_text
  color = $lockscreen_label_date_color
  font_size = $lockscreen_label_date_font_size
  font_family = $lockscreen_label_date_font_family
  position = $lockscreen_label_date_position
  halign = $lockscreen_label_date_halign
  valign = $lockscreen_label_date_valign
}

# TIME
label {
  monitor = 
  text = $lockscreen_label_time_text
  color = $lockscreen_label_time_color
  font_size = $lockscreen_label_time_font_size
  font_family = $lockscreen_label_time_font_family
  position = $lockscreen_label_time_position
  halign = $lockscreen_label_time_halign
  valign = $lockscreen_label_time_valign
}



# # Profile Picture
# image {
#     monitor =
#     path = /home/justin/Pictures/profile_pictures/justin_square.png
#     size = 100
#     border_size = 2
#     border_color = $window_active
#     position = 0, -100
#     halign = center
#     valign = center
# }